language: go

go:
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test $(go list ./... | grep -v /config4live-go/config4live) -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)